version: "3.8"

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
